# Generated by Django 3.1.5 on 2021-01-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exams', '0002_auto_20210105_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=1000, null=True)),
                ('question_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.questions')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.extendedusers')),
            ],
        ),
    ]
