# Generated by Django 3.1.5 on 2021-01-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_answers_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question_key',
            field=models.IntegerField(),
        ),
    ]
