# Generated by Django 3.1.5 on 2021-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_quiz_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='user_school',
            new_name='user',
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
